### ISSUE TITLE
Rich action messages (markup)

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/versionpress#1124]
Since #1075, VersionPress uses `actions.yml` file to describe actions and their messages. It would be useful to have richer messages for the GUI. 

For example, when someone clicks on "Hello World" in "Updated page 'Hello World'", it could show only commits related to this post. To do this, we need somehow describe that "Hello World" is a post and which post it is (VPID).

Possible solution 1 (more descriptive tags):

```
post:
  tags:
    VP-Post-Title: post_title
    VP-Post-Type: post_type
  actions:
    update: <action type=post/update>Updated</action> %VP-Post-Type% '<entity type=post vpid=%VPID%>%VP-Post-Title%</entity>'
```

Possible solution 2 (simple search tag):

```
post:
  tags:
    VP-Post-Title: post_title
    VP-Post-Type: post_type
  actions:
    update: <search query="action:post/update">Updated</search> %VP-Post-Type% '<search query="vpid:%VPID%">%VP-Post-Title%</search>'
```
