### ISSUE TITLE
Dynamic action priorities

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1232]
PR #1228 implemented new filter `vp_action_priority_{$scope}`, see [diff](https://github.com/versionpress/versionpress/pull/1228/files#diff-feab111b185fcb349da028835e5b80b5), but there has also been some discussion about other options. Specifically, @pavelevap noted that special WPLANG handling is not evident from the [`actions.yml`](https://github.com/versionpress/versionpress/blob/e900860b1cb990edcb3a309bd3818f6115ce2f04/plugins/versionpress/.versionpress/actions.yml#L28-L34) file and can be missed:

```yaml
option:
  actions:
    create: Created option '%VPID%'
    edit:
      message: Edited option '%VPID%'
      priority: 12
    delete: Deleted option '%VPID%'
```

That is true although it could be said for many other things in [hooks.php](https://github.com/versionpress/versionpress/blob/e900860b1cb990edcb3a309bd3818f6115ce2f04/plugins/versionpress/.versionpress/hooks.php). Still, we discussed with @JanVoracek what we could do about that. Some option would be something like this:

```yaml
option:
  actions:
    create:
      message: Created option '%VPID%'
      priority: 10
      priority(option_name==WPLANG): 20
 ```
 
 But it's not really accurate: in this case, the rule is more complex and would need to be something like:
 
 ```yaml
 option:
  actions:
    create:
      message: Created option '%VPID%'
      priority: 10
      priority(option_name=='WPLANG' && option_value==''): 20
 ```
 
 We're now basically embedding code into YAML which didn't look like a good idea.
 
Another idea was to call a function, similarly to what's possible [in schema.yml](https://github.com/versionpress/versionpress/blob/e900860b1cb990edcb3a309bd3818f6115ce2f04/plugins/versionpress/.versionpress/schema.yml#L17):

 ```yaml
 option:
  actions:
    create:
      message: Created option '%VPID%'
      priority: 10
      priority_WPLANG: @getWplangPriority
 ```
 
But that probably wouldn't work as determining priority doesn't seem to be deterministic here.

So it seems that the `vp_action_priority_{$scope}` filter as per #1228 is a reasonable solution for now, maybe combined with some comment in the YAML file (although, again, `hooks.php` is full of stuff to be aware of).
