### ISSUE TITLE
Plugin support – quick feedback & notes

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1347]
I'm creating this issue to gather quick feedback and notes, before it's all converted to full issues.

Feel free to post new items as comments.

**Comment by borekb** [comment]
We have `ignored-entities` and `ignored-columns` ([docs](https://github.com/versionpress/versionpress/blob/d867edc36512222ab24a6dc60b91775a0f12b758/docs/content/en/developer/plugin-support.md#ignoring-entities)), maybe simpler would be to call the former `ignored-rows`.

Current:

```yaml
post:
  ignored-entities:
    - 'post_type: revision'
    - 'post_status: auto-draft'
  ignored-columns:
    - comment_count: '@vp_fix_comments_count'
```

New:

```yaml
post:
  ignored-rows:
    - 'post_type: revision'
    - 'post_status: auto-draft'
  ignored-columns:
    - comment_count: '@vp_fix_comments_count'
```
