### ISSUE TITLE
Versionpress is not docker mount friendly during activation

### ISSUE THREAD

**Issue by ricxsar** [versionpress/versionpress#1456]
I tried to create a wordpress docker image with versionpress on it. I'm only interested on versionpress files so I created a mount point of git on wordpress root folder (/var/www/html/.git) and versionpress db folder (vpdb) on wp-content folder (/var/www/html/wp-content/vpdb).

On the checklist says `This website is already versioned in Git` even though the .git folder and vpdb is empty.

![image](https://user-images.githubusercontent.com/8968902/59729888-d640aa80-9272-11e9-8548-4959ea683691.png)

And also when i tried to activate it, it will try to delete the mounted folders which throws an error since it is not a normal folder.

I'm proposing is instead of deleting the folder, it should only delete the files inside it.

Another thing is when the docker image is deployed under a load balancer, it will not be successfully activated because mostly of the load balancers have limits on response time.

Please take the above situations on your design so that versionpress can be used on docker images.

More power and God bless us all.

**Comment by ricxsar** [comment]
To solve the problem when behind a load balancer, you should introduce a WP-CLI command which activates versionpress similar to the Wordpress Admin Plugin Activation.

**Comment by olexiyb** [comment]
Just create Dockerfile
```
FROM wordpress:latest

RUN apt-get update && apt-get install libldap2-dev -y
RUN docker-php-ext-install ldap
RUN apt-get install -y git
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
RUN wp core install --url="http://localhost:8000" --title=Site --admin_user=admin --admin_password=admin --admin_email=admin@gmail.com
RUN wp plugin install https://github.com/versionpress/versionpress/releases/download/4.0-beta2/versionpress-4.0-beta2.zip --activate
# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

And docker-compose.yml

```
version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wordpressdb
    volumes:
      - db:/var/lib/mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    image: blaizepress
    container_name: wordpressweb
    build: ./
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ".env"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - web:/var/www/html
volumes:
  web:
  db:
```
